name: 'Setup Emscripten toolchain'
description: 'Download emsdk and optionally install a version of Emscripten'
author: 'mymindstorm'
inputs:
  version:
    description: 'Version to install'
    default: 'latest'
  no-install:
    description: "If true will not download any version of Emscripten. emsdk will still be added to PATH."
    default: false
  no-cache:
    description: "If true will not cache any downloads with tc.cacheDir."
    default: false
  store-actions-cache:
    description: "If true will store files that could be cached in $GITHUB_WORKSPACE"
    default: false
  actions-cache-folder:
    description: "Set to the folder where your cached emsdk-master folder is."
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'download'
  color: 'green'
