name: "Run"
on: [pull_request, push]

jobs:
  defaults:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: mymindstorm/setup-emsdk@actions-cache

    - name: Verify
      run: emcc -v
  actions-use-cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache emsdk
        uses: actions/cache@v1
        id: cache
        with:
          path: emsdk-cache
          key: ${{ runner.os }}-emsdk-1.39.1
      - name: Setup emsdk (cache not found)  
        uses: mymindstorm/setup-emsdk@actions-cache
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          version: 1.39.1
          store-actions-cache: 'emsdk-cache'
      - name: Setup emsdk (cache found)        
        uses: mymindstorm/setup-emsdk@actions-cache
        if: steps.cache.outputs.cache-hit == 'true'
        with:
          version: 1.39.1
          actions-cache-folder: 'emsdk-cache'
      - name: Verify
        run: emcc -v
  no-install:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@actions-cache
        with:
          no-install: true

      - name: Verify
        run: emsdk list
